### ISSUE TITLE
F3 Doesn't work

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/MineCraft-One-Week-Challenge#51]
It is suppose to toggle the GUI, but for some reason it has stopped working.

**Comment by IridescentRose** [comment]
I think it has to do with the change to the Core context, since SFML uses OpenGL 1.1 to draw the GUI. It would be great if there was an implementation to modernize sprite drawing... but it's up to you. You could also just remove the patch for the MacOS contexts, as it seems it is an SFML bug, rather than a thing you can control.

**Comment by Hopson97** [comment]
Even if I uncomment the bool that has to be true to draw... it still doesn't draw. 

This is a pretty important thing :( Urgently needs fixing really.

**Comment by IridescentRose** [comment]
I got it working again. Sending a patch in a second, it's been fixed on my fork for a while, but I didn't realize you needed it immediately. Sorry! I didn't know that SFML used immediate mode for GUI drawing, I would assume that the library would use a modern OpenGL solution. My bad.

**Comment by Hopson97** [comment]
SFML last major update was in 2008, with many minor ones since. I hope they use modern in future versions :P 

Anyways, thank you!
